// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "@prisma/config"; // Correction de l'import ici

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Le "|| ''" évite les erreurs de typage TypeScript si DATABASE_URL n'est pas encore chargée
    url: process.env.DATABASE_URL || "", 
  },
});